// SPDX-FileCopyrightText: 2026 ArcheBase
//
// SPDX-License-Identifier: MulanPSL-2.0

//! Integration tests for RRD S3 streaming with real RRD files.
//!
//! These tests use actual RRD files generated by the RrdWriter to verify
//! that the S3 streaming parser works correctly with real-world data.

use std::fs;
use std::path::Path;

use robocodec::io::formats::rrd::stream::{
    MessageKind, RRD_STREAM_MAGIC, RrdMessageRecord, StreamingRrdParser,
};
use robocodec::io::s3::StreamingParser;

/// Helper function to load a test fixture file.
fn load_fixture(name: &str) -> Vec<u8> {
    let path = Path::new("tests/fixtures/rrd").join(name);
    fs::read(&path).unwrap_or_else(|_| panic!("Failed to read fixture: {}", name))
}

#[test]
fn test_real_rrd_small_uncompressed() {
    let data = load_fixture("small_uncompressed.rrd");

    // Verify magic
    assert_eq!(&data[0..4], RRD_STREAM_MAGIC);

    println!("File size: {}", data.len());

    let mut parser = StreamingRrdParser::new();
    let messages = parser.parse_chunk(&data).expect("Failed to parse RRD");

    println!("Parsed {} messages", messages.len());
    println!("Message count: {}", parser.message_count());
    println!("Initialized: {}", parser.is_initialized());
    println!("Has channels: {}", parser.has_channels());
    println!("Channel count: {}", parser.channels().len());

    // Should have parsed all 10 messages
    assert_eq!(messages.len(), 10);
    assert_eq!(parser.message_count(), 10);
    assert!(parser.is_initialized());
    assert!(parser.has_channels());
}

#[test]
fn test_real_rrd_medium_lz4() {
    let data = load_fixture("medium_lz4.rrd");

    // Verify magic
    assert_eq!(&data[0..4], RRD_STREAM_MAGIC);

    let mut parser = StreamingRrdParser::new();
    let messages = parser.parse_chunk(&data).expect("Failed to parse RRD");

    // Should have parsed all 100 messages
    assert_eq!(messages.len(), 100);
    assert_eq!(parser.message_count(), 100);
}

#[test]
fn test_real_rrd_large_multichannel() {
    let data = load_fixture("large_multichannel.rrd");

    // Verify magic
    assert_eq!(&data[0..4], RRD_STREAM_MAGIC);

    let mut parser = StreamingRrdParser::new();
    let messages = parser.parse_chunk(&data).expect("Failed to parse RRD");

    // Should have parsed all 200 messages
    // Note: RRF2 format doesn't have explicit channel IDs - entity paths are in Protobuf payload
    // Our simple fixtures use plain text, so all messages use the default topic
    assert_eq!(messages.len(), 200);
    assert_eq!(parser.message_count(), 200);
    assert_eq!(parser.channels().len(), 1); // Default topic for ArrowMsg
}

#[test]
fn test_real_rrd_timestamps() {
    let data = load_fixture("timestamps.rrd");

    // Verify magic
    assert_eq!(&data[0..4], RRD_STREAM_MAGIC);

    let mut parser = StreamingRrdParser::new();
    let messages = parser.parse_chunk(&data).expect("Failed to parse RRD");

    // Should have parsed all 25 messages
    assert_eq!(messages.len(), 25);
    assert_eq!(parser.message_count(), 25);

    // Verify message kind and topic
    for msg in &messages {
        assert_eq!(msg.kind, MessageKind::ArrowMsg);
        assert!(!msg.topic.is_empty());
    }
}

#[test]
fn test_real_rrd_chunked_parsing() {
    let data = load_fixture("large_multichannel.rrd");

    let mut parser = StreamingRrdParser::new();

    // Simulate streaming by parsing in chunks
    let chunk_size = 1024;
    let mut total_messages = 0;
    let mut offset = 0;

    while offset < data.len() {
        let end = (offset + chunk_size).min(data.len());
        let chunk = &data[offset..end];

        match parser.parse_chunk(chunk) {
            Ok(messages) => {
                let messages: Vec<RrdMessageRecord> = messages;
                total_messages += messages.len() as u64;
            }
            Err(e) => {
                // Expected when we need more data
                let error_msg = format!("{:?}", e);
                if !error_msg.contains("Need") && !error_msg.contains("require more") {
                    panic!("Unexpected error: {}", e);
                }
            }
        }

        offset = end;

        // Break if we've processed everything
        if total_messages >= 200 {
            break;
        }
    }

    // Verify we got all messages
    assert_eq!(parser.message_count(), 200);
}

#[test]
fn test_real_rrd_channel_info() {
    let data = load_fixture("large_multichannel.rrd");

    let mut parser = StreamingRrdParser::new();
    parser.parse_chunk(&data).expect("Failed to parse RRD");

    let channels = parser.channels();
    // RRF2 format uses entity paths from Protobuf payload, not numeric channel IDs
    // Our simple fixtures use plain text, so we get the default topic
    assert_eq!(channels.len(), 1);

    // Verify default topic exists
    assert!(channels.contains_key(&0));
    assert_eq!(channels[&0].topic, "/");
}

#[test]
fn test_real_rrd_message_content() {
    let data = load_fixture("small_uncompressed.rrd");

    let mut parser = StreamingRrdParser::new();
    let messages = parser.parse_chunk(&data).expect("Failed to parse RRD");

    // Check first message contains expected text
    let first_msg = &messages[0];
    assert!(first_msg.data.starts_with(b"message 0"));

    // Check last message
    let last_msg = &messages[messages.len() - 1];
    assert!(last_msg.data.starts_with(b"message 9"));
}

#[test]
fn test_all_rrd_fixtures_have_valid_magic() {
    let fixtures = vec![
        "small_uncompressed.rrd",
        "medium_lz4.rrd",
        "large_multichannel.rrd",
        "timestamps.rrd",
    ];

    for fixture in fixtures {
        let data = load_fixture(fixture);
        assert_eq!(
            &data[0..4],
            RRD_STREAM_MAGIC,
            "Fixture {} has invalid magic",
            fixture
        );
    }
}

// ----------------------------------------------------------------------------
// Tests with real rerun RRD files
// ----------------------------------------------------------------------------

#[test]
fn test_rerun_file1_parses() {
    let data = load_fixture("file1.rrd");

    // Verify RRF2 magic
    assert_eq!(&data[0..4], RRD_STREAM_MAGIC);

    let mut parser = StreamingRrdParser::new();
    let result = parser.parse_chunk(&data);

    // Should parse successfully
    assert!(
        result.is_ok(),
        "Failed to parse rerun file1.rrd: {:?}",
        result.err()
    );

    let messages = result.unwrap();
    println!("Parsed {} messages from file1.rrd", messages.len());

    // Should have parsed some messages
    assert!(!messages.is_empty());
    assert!(parser.is_initialized());
}

#[test]
fn test_rerun_file2_parses() {
    let data = load_fixture("file2.rrd");

    // Verify RRF2 magic
    assert_eq!(&data[0..4], RRD_STREAM_MAGIC);

    let mut parser = StreamingRrdParser::new();
    let result = parser.parse_chunk(&data);

    assert!(
        result.is_ok(),
        "Failed to parse rerun file2.rrd: {:?}",
        result.err()
    );

    let messages = result.unwrap();
    println!("Parsed {} messages from file2.rrd", messages.len());
    assert!(!messages.is_empty());
}

#[test]
fn test_rerun_file3_parses() {
    let data = load_fixture("file3.rrd");

    // Verify RRF2 magic
    assert_eq!(&data[0..4], RRD_STREAM_MAGIC);

    let mut parser = StreamingRrdParser::new();
    let result = parser.parse_chunk(&data);

    assert!(
        result.is_ok(),
        "Failed to parse rerun file3.rrd: {:?}",
        result.err()
    );

    let messages = result.unwrap();
    println!("Parsed {} messages from file3.rrd", messages.len());
    assert!(!messages.is_empty());
}

#[test]
fn test_rerun_all_files_have_valid_magic() {
    let rerun_files = vec!["file1.rrd", "file2.rrd", "file3.rrd"];

    for filename in rerun_files {
        let data = load_fixture(filename);
        assert_eq!(
            &data[0..4],
            RRD_STREAM_MAGIC,
            "Rerun file {} has invalid magic",
            filename
        );
    }
}

// ----------------------------------------------------------------------------
// Comprehensive tests for all 20 rerun RRD files
// ----------------------------------------------------------------------------

#[test]
fn test_rerun_all_files_parse() {
    let rerun_files = vec![
        "file1.rrd",
        "file2.rrd",
        "file3.rrd",
        "file4.rrd",
        "file5.rrd",
        "file6.rrd",
        "file7.rrd",
        "file8.rrd",
        "file9.rrd",
        "file10.rrd",
        "file11.rrd",
        "file12.rrd",
        "file13.rrd",
        "file14.rrd",
        "file15.rrd",
        "file16.rrd",
        "file17.rrd",
        "file18.rrd",
        "file19.rrd",
        "file20.rrd",
    ];

    let mut total_messages = 0;
    let mut total_files = 0;

    for filename in rerun_files {
        let data = load_fixture(filename);

        // Verify RRF2 magic
        assert_eq!(
            &data[0..4],
            RRD_STREAM_MAGIC,
            "Rerun file {} has invalid magic",
            filename
        );

        let mut parser = StreamingRrdParser::new();
        match parser.parse_chunk(&data) {
            Ok(messages) => {
                let msg_count = messages.len();
                total_messages += msg_count;
                total_files += 1;
                println!("{}: {} messages", filename, msg_count);
                assert!(
                    msg_count > 0,
                    "{} should have at least one message",
                    filename
                );
            }
            Err(e) => {
                panic!("Failed to parse {}: {:?}", filename, e);
            }
        }
    }

    println!("Total: {} files, {} messages", total_files, total_messages);
    assert_eq!(total_files, 20, "All 20 rerun files should parse");
}
